# -*- coding: utf-8 -*-
"""Language_detection_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrejCgwxUAPdAXkSsXzENmI2ebCzsywa
"""

import numpy as np
import pandas as pd

data = pd.read_csv("data/language.csv")


from sklearn.feature_extraction.text import CountVectorizer

from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import MultinomialNB

data.isnull().sum()

data['language'].value_counts()

data.dtypes

x= np.array(data['Text'])
y=np.array(data['language'])

cv= CountVectorizer()
X= cv.fit_transform(x)

X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

model= MultinomialNB()

model.fit(X_train,y_train)

model.score(X_test,y_test)

user = input("Enter a text")
data_point = cv.transform([user])
output=model.predict(data_point)
print(output)
